### ISSUE TITLE
File "src/jbuild", line 18, characters 17-40: # Error: "ocaml-migrate-parsetree" is not a ppx driver during the opam upgrade with dune-1.0

### ISSUE THREAD

**Issue by XVilka** [ocaml-ppx/ppxlib#36]
```

#=== ERROR while compiling ppxlib.0.2.1 =======================================#
# context     2.0.0~rc3 | linux/x86_64 | ocaml-system.4.06.0 | file:///home/akochkov/data/tmp/opam-repository
# path        ~/.opam/default/.opam-switch/build/ppxlib.0.2.1
# command     ~/.opam/default/bin/jbuilder build -p ppxlib -j 7
# exit-code   1
# env-file    ~/.opam/log/ppxlib-630120-bf8001.env
# output-file ~/.opam/log/ppxlib-630120-bf8001.out
### output ###
# File "src/jbuild", line 18, characters 17-40:
# Error: "ocaml-migrate-parsetree" is not a ppx driver



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ppxlib 0.2.1
└─ 
```

**Comment by xclerc** [comment]
I stumbled upon this one yesterday.

The fix, as provided to me by @diml, is to reinstall
`ocaml-migrate-parsetree` **after** installing the `dune`
package.

**Comment by diml** [comment]
This should be fixed since [this PR](https://github.com/ocaml/opam-repository/pull/12350)

**Comment by basus** [comment]
The referenced PR seems to have been merged, but I'm still getting the original error. I'm running OCaml 4.06.1 and OPAM 1.2.2 on Arch Linux.

**Comment by diml** [comment]
If you do `opam update` followed by `opam upgrade`, does it reinstall ocaml-migrate-parsetree?

**Comment by neojski** [comment]
Doing `opam update && upam upgrade` didn't fix it for me but doing `opam uninstall ocaml-migrate-parsetree && opam install ocaml-migrate-parsetree` did the trick and I was able to install core after that. I'm using ocaml 4.06.0 and opam 1.2.2.

**Comment by cfcs** [comment]
This is broken for me too, latest version of opam, on debian.

**Comment by cfcs** [comment]
perhaps we could update the constraint in the `opam` file to be `= 1.0.11` since `>= 1.0.9` doesn't seem to work?

**Comment by XVilka** [comment]
I am closing it as solved.
